history_size: 50
dropdown_size: 20
terminal_launch: urxvt --title "%TITLE%" --hold -e bash -c "%COMMAND%"
colors:
  normal:
   foreground: '#00A1FF'
   background: '#000000'
  selected:
   foreground: '#000000'
   background: '#00A1FF'
path: ''
exclude_path: '/bin,/usr/sbin,/sbin'
exclude: 'ls,cd'
alternative_theme: 'light'
themes:
  boje:
    gtk_theme: 'Boje-Orange'
    gtkrc: '/home/ghardo/.themes/Boje-Orange/gtk-2.0/gtkrc'
  light:
    gtk_theme: 'ManjaroFlatLight'
    gtkrc: '/usr/share/themes/ManjaroFlatLight/gtk-2.0/gtkrc'
apps:
  keepassx:
    theme: 'light'
    terminal: false
  GitEye:
    theme: 'light'
    terminal: false
  filezilla:
    theme: 'light'
    terminal: false
  gitg:
    theme: 'light'
    terminal: false
  iftop:
    terminal: true
    sudo: true
  htop:
    terminal: true
alias:
  mysqlide:
    theme: 'light'
    terminal: false
    command: 'phpstorm /home/ghardo/work/mysql/'
  logcat:
    terminal: true
    command: 'adb logcat | /home/ghardo/bin/logcat-colorize'
